
CREATE TABLE "product_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

ALTER TABLE "products" ADD "category" INT;
ALTER TABLE "products" ADD FOREIGN KEY ("category") REFERENCES "product_categories" ("id");
