// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID          int32            `json:"id"`
	Oid         string           `json:"oid"`
	Uid         string           `json:"uid"`
	TotalAmount int32            `json:"total_amount"`
	OrderStatus int32            `json:"order_status"`
	OrderedAt   pgtype.Timestamp `json:"ordered_at"`
}

type OrderItem struct {
	ID       int32  `json:"id"`
	Oid      string `json:"oid"`
	Pid      string `json:"pid"`
	Quantity int32  `json:"quantity"`
	Amount   int32  `json:"amount"`
}

type Product struct {
	ID          int32       `json:"id"`
	Pid         string      `json:"pid"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Stock       int32       `json:"stock"`
	Price       int32       `json:"price"`
	Category    pgtype.Int4 `json:"category"`
}

type ProductCategory struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID         int32            `json:"id"`
	Uid        string           `json:"uid"`
	Email      string           `json:"email"`
	FirstName  string           `json:"first_name"`
	LastName   pgtype.Text      `json:"last_name"`
	Password   string           `json:"password"`
	DateJoined pgtype.Timestamp `json:"date_joined"`
}
