name: Deploy

on:
  workflow_run:
    workflows:
      - Docker
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: sudo docker pull lovelyoyrmia/ecommerce-api:latest

    - name: Run Docker Container
      run: sudo docker run -d -p 50052:50052 --name lovelyoyrmia/ecommerce-api
    