name: Docker

on:
  push:
    branches: [ "release" ]

jobs:
  build:
    name: Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build Docker Image
      run: docker compose -f docker-compose.yaml build
    
    - name: Added New Tag
      run: docker tag ecommerce-api:latest lovelyoyrmia/ecommerce-api:latest

    - name: Push to Dockerhub
      run: docker push lovelyoyrmia/ecommerce-api:latest
  
  deploy:
    name: Deploy To Ec2
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull lovelyoyrmia/ecommerce-api:latest
      - name: Delete Previous Container
        run: sudo docker rm ecommerce-api
      - name: Run Docker Container
        run: sudo docker run --name ecommerce-api -p 50052:50052 lovelyoyrmia/ecommerce-api:latest